[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "istanbul"
etherscan_api_key = "${BSCSCAN_API_KEY}"


[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.3.0-rc.0"

[rpc_endpoints]
airdao = "https://network.ambrosus.io"
bscTestnet = "https://bsc-testnet.drpc.org"
ethereum = "https://mainnet.infura.io/v3/16c76d6261f5415b80c2911cbcc89d2d"
bscMainnet = "https://bsc-dataseed.binance.org/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
